In [2]:
import scipy as sp
import numpy as np

a = np.array_split(range(10), 4)
print a

print "hihi"

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7]), array([8, 9])]
hihi


In [30]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])
print a
print a.ndim
print a.shape

b = a.reshape(3, 2)
print b
print b.ndim
print b.shape


[1 2 3 4 5 6]
1
(6,)
[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)


In [31]:
c = a.reshape(3, 2).copy()
c[0][0] = 11
print c
print a

[[11  2]
 [ 3  4]
 [ 5  6]]
[1 2 3 4 5 6]


In [42]:
a[np.array([2, 3, 4])]
a.clip(0, 5)

array([1, 2, 3, 4, 5, 5])

In [48]:
import timeit
normal_py_sec = timeit.timeit('sum(x*x for x in xrange(1000))',
number=10000)
naive_np_sec = timeit.timeit('sum(na*na)',
setup="import numpy as np; na=np.arange(1000)",
number=10000)
good_np_sec = timeit.timeit('na.dot(na)',
setup="import numpy as np; na=np.arange(1000)",
number=10000)

print("Normal Python: %f sec"%normal_py_sec)
print("Naive NumPy: %f sec"%naive_np_sec)
print("Good NumPy: %f sec"%good_np_sec)

Normal Python: 0.662777 sec
Naive NumPy: 0.921280 sec
Good NumPy: 0.013468 sec
